// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plugins.DataStore.SQL;

#nullable disable

namespace Plugins.DataStore.SQL.Migrations
{
    [DbContext(typeof(MarketContext))]
    partial class MarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreBusiness.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apparel and fashion",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Food and groceries",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Home furniture",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Books and literature",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Toys for kids",
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sports equipment",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Beauty products",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Automotive accessories",
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Jewelry and accessories",
                            Name = "Jewelry"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Smartphone",
                            Price = 799.99000000000001,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 1299.99,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Shirt",
                            Price = 29.989999999999998,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Jeans",
                            Price = 49.990000000000002,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Apple",
                            Price = 1.99,
                            Quantity = 500
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Banana",
                            Price = 0.98999999999999999,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "Sofa",
                            Price = 499.99000000000001,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Name = "Coffee Table",
                            Price = 129.99000000000001,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Name = "Novel",
                            Price = 19.989999999999998,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            Name = "Toy Car",
                            Price = 9.9900000000000002,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 7,
                            Name = "Football",
                            Price = 25.989999999999998,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            Name = "Soccer Shoes",
                            Price = 49.990000000000002,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            Name = "Lipstick",
                            Price = 15.99,
                            Quantity = 150
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 8,
                            Name = "Shampoo",
                            Price = 9.9900000000000002,
                            Quantity = 250
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 9,
                            Name = "Car Battery",
                            Price = 79.989999999999995,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 9,
                            Name = "Car Wash Kit",
                            Price = 19.989999999999998,
                            Quantity = 75
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 10,
                            Name = "Ring",
                            Price = 299.99000000000001,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 10,
                            Name = "Necklace",
                            Price = 199.99000000000001,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Name = "Smartwatch",
                            Price = 149.99000000000001,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Name = "Headphones",
                            Price = 79.989999999999995,
                            Quantity = 150
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Name = "Sweater",
                            Price = 39.990000000000002,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Name = "Jacket",
                            Price = 89.989999999999995,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Name = "Water Bottle",
                            Price = 5.9900000000000002,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Name = "Soda",
                            Price = 2.9900000000000002,
                            Quantity = 400
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Name = "Washing Machine",
                            Price = 399.99000000000001,
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("CoreBusiness.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeforeQty")
                        .HasColumnType("int");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeforeQty = 50,
                            CashierName = "Alice",
                            Price = 799.99000000000001,
                            ProductId = 1,
                            ProductName = "Smartphone",
                            SoldQty = 5,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1707)
                        },
                        new
                        {
                            Id = 2,
                            BeforeQty = 30,
                            CashierName = "Bob",
                            Price = 1299.99,
                            ProductId = 2,
                            ProductName = "Laptop",
                            SoldQty = 3,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1731)
                        },
                        new
                        {
                            Id = 3,
                            BeforeQty = 100,
                            CashierName = "Charlie",
                            Price = 29.989999999999998,
                            ProductId = 3,
                            ProductName = "Shirt",
                            SoldQty = 10,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1736)
                        },
                        new
                        {
                            Id = 4,
                            BeforeQty = 60,
                            CashierName = "Diana",
                            Price = 49.990000000000002,
                            ProductId = 4,
                            ProductName = "Jeans",
                            SoldQty = 8,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1740)
                        },
                        new
                        {
                            Id = 5,
                            BeforeQty = 500,
                            CashierName = "Eve",
                            Price = 1.99,
                            ProductId = 5,
                            ProductName = "Apple",
                            SoldQty = 50,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1743)
                        },
                        new
                        {
                            Id = 6,
                            BeforeQty = 300,
                            CashierName = "Frank",
                            Price = 0.98999999999999999,
                            ProductId = 6,
                            ProductName = "Banana",
                            SoldQty = 40,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1747)
                        },
                        new
                        {
                            Id = 7,
                            BeforeQty = 10,
                            CashierName = "Grace",
                            Price = 499.99000000000001,
                            ProductId = 7,
                            ProductName = "Sofa",
                            SoldQty = 1,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1750)
                        },
                        new
                        {
                            Id = 8,
                            BeforeQty = 25,
                            CashierName = "Hannah",
                            Price = 129.99000000000001,
                            ProductId = 8,
                            ProductName = "Coffee Table",
                            SoldQty = 3,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1754)
                        },
                        new
                        {
                            Id = 9,
                            BeforeQty = 200,
                            CashierName = "Isaac",
                            Price = 19.989999999999998,
                            ProductId = 9,
                            ProductName = "Novel",
                            SoldQty = 20,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1757)
                        },
                        new
                        {
                            Id = 10,
                            BeforeQty = 100,
                            CashierName = "Jack",
                            Price = 9.9900000000000002,
                            ProductId = 10,
                            ProductName = "Toy Car",
                            SoldQty = 15,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1760)
                        },
                        new
                        {
                            Id = 11,
                            BeforeQty = 50,
                            CashierName = "Katherine",
                            Price = 25.989999999999998,
                            ProductId = 11,
                            ProductName = "Football",
                            SoldQty = 8,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1764)
                        },
                        new
                        {
                            Id = 12,
                            BeforeQty = 35,
                            CashierName = "Leo",
                            Price = 49.990000000000002,
                            ProductId = 12,
                            ProductName = "Soccer Shoes",
                            SoldQty = 5,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1767)
                        },
                        new
                        {
                            Id = 13,
                            BeforeQty = 150,
                            CashierName = "Mia",
                            Price = 15.99,
                            ProductId = 13,
                            ProductName = "Lipstick",
                            SoldQty = 10,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1772)
                        },
                        new
                        {
                            Id = 14,
                            BeforeQty = 250,
                            CashierName = "Noah",
                            Price = 9.9900000000000002,
                            ProductId = 14,
                            ProductName = "Shampoo",
                            SoldQty = 30,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1776)
                        },
                        new
                        {
                            Id = 15,
                            BeforeQty = 40,
                            CashierName = "Olivia",
                            Price = 79.989999999999995,
                            ProductId = 15,
                            ProductName = "Car Battery",
                            SoldQty = 3,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1779)
                        },
                        new
                        {
                            Id = 16,
                            BeforeQty = 75,
                            CashierName = "Paul",
                            Price = 19.989999999999998,
                            ProductId = 16,
                            ProductName = "Car Wash Kit",
                            SoldQty = 7,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1782)
                        },
                        new
                        {
                            Id = 17,
                            BeforeQty = 15,
                            CashierName = "Quinn",
                            Price = 299.99000000000001,
                            ProductId = 17,
                            ProductName = "Ring",
                            SoldQty = 1,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1786)
                        },
                        new
                        {
                            Id = 18,
                            BeforeQty = 20,
                            CashierName = "Rachel",
                            Price = 199.99000000000001,
                            ProductId = 18,
                            ProductName = "Necklace",
                            SoldQty = 2,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1789)
                        },
                        new
                        {
                            Id = 19,
                            BeforeQty = 100,
                            CashierName = "Sam",
                            Price = 149.99000000000001,
                            ProductId = 19,
                            ProductName = "Smartwatch",
                            SoldQty = 20,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1792)
                        },
                        new
                        {
                            Id = 20,
                            BeforeQty = 150,
                            CashierName = "Tina",
                            Price = 79.989999999999995,
                            ProductId = 20,
                            ProductName = "Headphones",
                            SoldQty = 30,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1795)
                        },
                        new
                        {
                            Id = 21,
                            BeforeQty = 80,
                            CashierName = "Ursula",
                            Price = 39.990000000000002,
                            ProductId = 21,
                            ProductName = "Sweater",
                            SoldQty = 10,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1799)
                        },
                        new
                        {
                            Id = 22,
                            BeforeQty = 40,
                            CashierName = "Victor",
                            Price = 89.989999999999995,
                            ProductId = 22,
                            ProductName = "Jacket",
                            SoldQty = 5,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1802)
                        },
                        new
                        {
                            Id = 23,
                            BeforeQty = 200,
                            CashierName = "Wendy",
                            Price = 5.9900000000000002,
                            ProductId = 23,
                            ProductName = "Water Bottle",
                            SoldQty = 35,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1805)
                        },
                        new
                        {
                            Id = 24,
                            BeforeQty = 400,
                            CashierName = "Xander",
                            Price = 2.9900000000000002,
                            ProductId = 24,
                            ProductName = "Soda",
                            SoldQty = 50,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1808)
                        },
                        new
                        {
                            Id = 25,
                            BeforeQty = 20,
                            CashierName = "Yara",
                            Price = 399.99000000000001,
                            ProductId = 25,
                            ProductName = "Washing Machine",
                            SoldQty = 3,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1812)
                        },
                        new
                        {
                            Id = 26,
                            BeforeQty = 45,
                            CashierName = "Alice",
                            Price = 799.99000000000001,
                            ProductId = 1,
                            ProductName = "Smartphone",
                            SoldQty = 10,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1815)
                        },
                        new
                        {
                            Id = 27,
                            BeforeQty = 28,
                            CashierName = "Bob",
                            Price = 1299.99,
                            ProductId = 2,
                            ProductName = "Laptop",
                            SoldQty = 4,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1818)
                        },
                        new
                        {
                            Id = 28,
                            BeforeQty = 300,
                            CashierName = "Frank",
                            Price = 0.98999999999999999,
                            ProductId = 6,
                            ProductName = "Banana",
                            SoldQty = 60,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1821)
                        },
                        new
                        {
                            Id = 29,
                            BeforeQty = 10,
                            CashierName = "Grace",
                            Price = 499.99000000000001,
                            ProductId = 7,
                            ProductName = "Sofa",
                            SoldQty = 2,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1825)
                        },
                        new
                        {
                            Id = 30,
                            BeforeQty = 25,
                            CashierName = "Hannah",
                            Price = 129.99000000000001,
                            ProductId = 8,
                            ProductName = "Coffee Table",
                            SoldQty = 4,
                            TimeStamp = new DateTime(2025, 3, 9, 7, 34, 47, 478, DateTimeKind.Local).AddTicks(1828)
                        });
                });

            modelBuilder.Entity("CoreBusiness.Product", b =>
                {
                    b.HasOne("CoreBusiness.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoreBusiness.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
